services:
  app:
    build: ./backend
    container_name: medical_appointment_service_app
    ports:
      - "8000:8000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://{{ db_host }}:{{ db_port }}/medical_appointments
      - SPRING_DATASOURCE_USERNAME={{ db_user }}
      - SPRING_DATASOURCE_PASSWORD={{ db_password }}
      - SPRING_MAIL_HOST={{ mail_host }}
      - SPRING_MAIL_PORT={{ mail_port }}
    depends_on:
      - mailhog

  frontend:
    build: ./frontend
    container_name: medical_appointment_service_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://{{ backend_host }}:8000

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI
