version: '3.8'

services:
  app:
    build: .
    container_name: medical_appointment_service_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:password@your-db-vm-ip:5432/medical_appointments
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
    depends_on:
      - mailhog

  frontend:
    build: ./frontend
    container_name: medical_appointment_service_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI
